"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CoinIcon = void 0;
var React = require("react");
var eth = require("./icons/eth.png");
var btc = require("./icons/btc.png");
var dash = require("./icons/dash.png");
var bch = require("./icons/bch.png");
var bsv = require("./icons/bsv.png");
var ltc = require("./icons/ltc.png");
var zec = require("./icons/zec.png");
var btg = require("./icons/btg.png");
var xrp = require("./icons/xrp.png");
var xlm = require("./icons/xlm.png");
var omg = require("./icons/omg.png");
var tusd = require("./icons/tusd.png");
var gusd = require("./icons/gusd.png");
var pax = require("./icons/pax.png");
var usdc = require("./icons/usdc.png");
var dai = require("./icons/dai.png");
var mcdai = require("./icons/mcdai.png");
var cel = require("./icons/cel.png");
var zrx = require("./icons/zrx.png");
var orbs = require("./icons/orbs.png");
var usdterc20 = require("./icons/usdterc20.png");
var tgbp = require("./icons/tgbp.png");
var taud = require("./icons/taud.png");
var thkd = require("./icons/thkd.png");
var tcad = require("./icons/tcad.png");
var eos = require("./icons/eos.png");
var sga = require("./icons/sga.png");
var xaut = require("./icons/xaut.png");
var etc = require("./icons/etc.png");
var icons = Object.freeze({ eth: eth, btc: btc, dash: dash, bch: bch, bsv: bsv, ltc: ltc, zec: zec, btg: btg, xrp: xrp, xlm: xlm, omg: omg, tusd: tusd, gusd: gusd, pax: pax, usdc: usdc, dai: dai, zrx: zrx, cel: cel, mcdai: mcdai, orbs: orbs, usdterc20: usdterc20, tgbp: tgbp, taud: taud, thkd: thkd, tcad: tcad, eos: eos, sga: sga, xaut: xaut, etc: etc });
;
exports.CoinIcon = function (props) {
    return (React.createElement("img", { src: icons[props.currency.toLowerCase().replace(" ", "")], alt: props.currency }));
};
//# sourceMappingURL=CoinIcons.js.map